Repository AndrewVolostnykh/dsaimplementation, pull requests merged in 2020-05, with the labels that each got.

#3 Close #1 Close #2
  Algorithms/Conversations/README.md
  Algorithms/Conversations/roman_conversation/README.md
  DS/FIFO/README.md
  DS/LIFO/README.md
  DS/List/README.md
  DS/Map/README.md
  DS/Tree/README.md
  README.md
Labels: documentation

#7 Create LICENSE
  LICENSE
Labels: enhancement

#8 License added
  LICENSE
Labels: enhancement

#13 Develop java (Roman-Decimal convertion)
  Algorithms/Conversations/roman_conversation/ConvertRoman.java
Labels: enhancement, java

#14 (Java) Roman to dec and back
  Algorithms/Conversations/roman_conversation/ConvertRoman.java
  Tasks/README.md
Labels: enhancement
